# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGFSDyHlN8W9_3hbQxrwkzvIGGvcVc2A
"""

import streamlit as st
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
from typing import Dict

# ==========================================
# 1. NÚCLEO MATEMÁTICO (Cálculo de la Función de Pérdida)
# ==========================================
class LossFunctionModel:
    """Procesa la función de pérdida y calcula gradientes simbólicos."""
    def __init__(self, equation_str: str):
        self.w1, self.w2 = sp.symbols('w1 w2') # w1 y w2 representan los Pesos del modelo
        # Reemplazamos x,y por w1,w2 para que el usuario pueda escribir con x e y por costumbre
        eq_adaptada = equation_str.replace('x', 'w1').replace('y', 'w2')
        self.expr = sp.sympify(eq_adaptada)

        self._f_eval = sp.lambdify((self.w1, self.w2), self.expr, 'numpy')
        self._grad_w1 = sp.lambdify((self.w1, self.w2), sp.diff(self.expr, self.w1), 'numpy')
        self._grad_w2 = sp.lambdify((self.w1, self.w2), sp.diff(self.expr, self.w2), 'numpy')

    def evaluate(self, w1_val, w2_val):
        return self._f_eval(w1_val, w2_val)

    def gradient(self, point: np.ndarray) -> np.ndarray:
        return np.array([float(self._grad_w1(point[0], point[1])),
                         float(self._grad_w2(point[0], point[1]))])

# ==========================================
# 2. MOTOR DE ENTRENAMIENTO (Optimizador)
# ==========================================
class GradientDescentOptimizer:
    """Ajusta los pesos del modelo utilizando Gradiente Descendente con Inercia."""
    def __init__(self, learning_rate=0.001, max_epochs=1000, tolerance=1e-6, momentum=0.9):
        self.lr = learning_rate
        self.max_epochs = max_epochs
        self.tolerance = tolerance
        self.momentum = momentum

    def train(self, model: LossFunctionModel, initial_weights: np.ndarray) -> Dict:
        path = [initial_weights.copy()]
        loss_history = [model.evaluate(initial_weights[0], initial_weights[1])]

        current_weights = initial_weights.copy()
        velocity = np.zeros(2)

        for _ in range(self.max_epochs):
            grad = model.gradient(current_weights)

            # Regla de actualización de pesos
            velocity = self.momentum * velocity - self.lr * grad
            next_weights = current_weights + velocity

            path.append(next_weights.copy())
            loss_val = model.evaluate(next_weights[0], next_weights[1])
            loss_history.append(loss_val)

            # Criterios de parada matemático (Gradiente cercano a cero o error infinito)
            if np.linalg.norm(grad) < self.tolerance or np.isinf(loss_val) or np.isnan(loss_val) or loss_val > 1e15:
                current_weights = next_weights
                break

            current_weights = next_weights

        return {'optimal_weights': current_weights, 'path': path, 'loss_history': loss_history}

# ==========================================
# 3. DIAGNÓSTICO DEL MODELO
# ==========================================
class ModelDiagnostic:
    @staticmethod
    def analyze(results: Dict, max_epochs: int) -> str:
        history = results['loss_history']
        epochs = len(history) - 1

        if np.isnan(history[-1]) or np.isinf(history[-1]) or history[-1] > history[0] * 100:
            return "🚨 **DIVERGENCIA (Explosión del Gradiente):** La Tasa de Aprendizaje es muy alta. El modelo no pudo aprender."

        subidas = sum(1 for i in range(1, len(history)) if history[i] > history[i-1])
        if subidas > epochs * 0.1:
            return "⚠️ **OSCILACIÓN EXCESIVA:** El modelo rebota demasiado en la superficie de error. Reduce el Learning Rate."

        if epochs >= max_epochs:
            return "🐢 **ESTANCAMIENTO:** Faltaron épocas para minimizar la pérdida por completo o el Learning Rate es muy bajo."

        return f"✅ **ENTRENAMIENTO EXITOSO:** Convergencia alcanzada y error minimizado en {epochs} épocas."

# ==========================================
# 4. INTERFAZ WEB (STREAMLIT)
# ==========================================
st.set_page_config(page_title="Entrenamiento ML - Optimizador", layout="wide")

st.title("🧠 Simulador de Entrenamiento: Optimización de Función de Pérdida")
st.markdown("Ajuste de pesos mediante Gradiente Descendente para modelos de Machine Learning.")

# --- BARRA LATERAL (Hiperparámetros) ---
st.sidebar.header("⚙️ Hiperparámetros de Red")

ecuacion = st.sidebar.text_input("Función de Pérdida f(x,y):", value="(1 - x)**2 + 100 * (y - x**2)**2")
st.sidebar.caption("Nota: Internamente x e y representan los pesos W1 y W2 del modelo.")

lr = st.sidebar.number_input("Tasa de Aprendizaje (Learning Rate):", value=0.001, format="%.5f")
epochs = st.sidebar.slider("Épocas Máximas (Iteraciones):", min_value=100, max_value=10000, value=5000, step=100)
momentum = st.sidebar.slider("Momentum (Inercia):", min_value=0.0, max_value=0.99, value=0.9, step=0.01)

st.sidebar.subheader("📍 Inicialización de Pesos")
usar_aleatorio = st.sidebar.checkbox("Inicialización Aleatoria", value=True)

if usar_aleatorio:
    w1_init = np.random.uniform(-3.0, 3.0)
    w2_init = np.random.uniform(-3.0, 3.0)
    st.sidebar.info(f"Pesos iniciales: W1={w1_init:.2f}, W2={w2_init:.2f}")
else:
    w1_init = st.sidebar.number_input("Peso Inicial W1:", value=-1.2)
    w2_init = st.sidebar.number_input("Peso Inicial W2:", value=1.0)

# --- EJECUCIÓN ---
if st.sidebar.button("▶️ Entrenar Modelo", type="primary"):
    try:
        model = LossFunctionModel(ecuacion)
        optimizer = GradientDescentOptimizer(learning_rate=lr, max_epochs=epochs, momentum=momentum)

        with st.spinner('Entrenando el modelo y ajustando pesos...'):
            results = optimizer.train(model, np.array([w1_init, w2_init]))

        opt_weights = results['optimal_weights']
        min_loss = results['loss_history'][-1]

        # Panel de Métricas
        col1, col2, col3 = st.columns(3)
        col1.metric("Peso Óptimo W1", f"{opt_weights[0]:.5f}")
        col2.metric("Peso Óptimo W2", f"{opt_weights[1]:.5f}")
        col3.metric("Error Final (Loss)", f"{min_loss:.5f}")

        # Diagnóstico
        diagnostico = ModelDiagnostic.analyze(results, epochs)
        if "EXITOSO" in diagnostico:
            st.success(diagnostico)
        elif "DIVERGENCIA" in diagnostico or "ESTANCAMIENTO" in diagnostico:
            st.error(diagnostico)
        else:
            st.warning(diagnostico)

        # Gráficas
        st.subheader("Análisis Visual del Entrenamiento")
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

        path = np.array(results['path'])
        px, py = path[:, 0], path[:, 1]
        history = results['loss_history']

        margen = 2.0
        w1_min, w1_max = min(w1_init, opt_weights[0]) - margen, max(w1_init, opt_weights[0]) + margen
        w2_min, w2_max = min(w2_init, opt_weights[1]) - margen, max(w2_init, opt_weights[1]) + margen

        W1, W2 = np.meshgrid(np.linspace(w1_min, w1_max, 200), np.linspace(w2_min, w2_max, 200))
        Loss_Surface = model.evaluate(W1, W2)

        # Gráfica 1: Superficie de Error
        contour = ax1.contour(W1, W2, Loss_Surface, levels=40, cmap='viridis', alpha=0.8)
        fig.colorbar(contour, ax=ax1, label='Magnitud del Error')
        ax1.plot(px, py, marker='.', color='red', linestyle='-', linewidth=1.5, label='Ruta de Ajuste')
        ax1.plot(px[0], py[0], marker='s', color='blue', markersize=8, label='Pesos Iniciales')
        ax1.plot(px[-1], py[-1], marker='*', color='gold', markersize=14, label='Pesos Óptimos')
        ax1.set_title('Topografía de la Función de Pérdida')
        ax1.set_xlabel('Peso W1')
        ax1.set_ylabel('Peso W2')
        ax1.legend()
        ax1.grid(True, alpha=0.3)

        # Gráfica 2: Curva de Convergencia
        ax2.plot(range(len(history)), history, color='purple', linewidth=2)
        ax2.set_title('Curva de Aprendizaje (Convergencia)')
        ax2.set_xlabel('Épocas (Iteraciones)')
        ax2.set_ylabel('Error (Loss)')
        ax2.set_yscale('symlog')
        ax2.grid(True, alpha=0.3)

        plt.tight_layout()
        st.pyplot(fig)

    except Exception as e:
        st.error(f"Error en la estructura matemática de la red: {e}")
else:
    st.info("👈 Configura los hiperparámetros en el panel lateral y presiona 'Entrenar Modelo'.")